import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/ui/footer";
import Header from "@/components/ui/header";

export const metadata: Metadata = {
	title: "Movie Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased dark">
				<Header />
				<main className="flex flex-col">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
